Add iterator concept checking in buffer<> constructor to calm down gcc-4.9
gcc believes it can creates a buffer<> from ( int, int ) and then create a buffer from it whereas we expect to have an implicit range<> creation to construct the buffer<> from :

g++-4.9 -Wall -std=c++1y -I/goutte/AMD/Projects/OpenCL/triSYCL/include -I/goutte/AMD/Projects/OpenCL/triSYCL/tests/common -fopenmp    accessor.cpp   -o accessor
accessor.cpp: In function ‘int main()’:
accessor.cpp:17:40: error: call of overloaded ‘buffer(<brace-enclosed initializer list>)’ is ambiguous
     cl::sycl::buffer<int, 2> b({ N, M });
                                        ^
accessor.cpp:17:40: note: candidates are:
In file included from accessor.cpp:3:0:
/goutte/AMD/Projects/OpenCL/triSYCL/include/CL/sycl.hpp:1013:12: note: cl::sycl::buffer<T, dimensions>::buffer(const cl::sycl::range<dimensions>&) [with T = int; long unsigned int dimensions = 2ul]
   explicit buffer(const range<dimensions> &r)
            ^
/goutte/AMD/Projects/OpenCL/triSYCL/include/CL/sycl.hpp:987:8: note: cl::sycl::buffer<int, 2ul>::buffer(const cl::sycl::buffer<int, 2ul>&)
 struct buffer {
        ^
/goutte/AMD/Projects/OpenCL/triSYCL/include/CL/sycl.hpp:987:8: note: cl::sycl::buffer<int, 2ul>::buffer(cl::sycl::buffer<int, 2ul>&&)
<builtin>: recipe for target 'accessor' failed
make: *** [accessor] Error 1